In [1]:
import numpy as np

In [2]:
data = np.random.randint(-10,10,20)

In [3]:
data

array([ 2,  7, -3,  7, -5,  6,  2, -6, -3, -8,  2,  6,  5, -5,  0, -6,  4,
        4, -5, -4])

In [4]:
np.argmax(data)

1

In [5]:
np.argmin(data)

9

In [6]:
np.argsort(data)

array([ 9, 15,  7, 13, 18,  4, 19,  8,  2, 14, 10,  6,  0, 16, 17, 12,  5,
       11,  3,  1])

In [7]:
X = np.array([[66,22,11],
          [22,11,2],
          [31,21,65]])

In [9]:
X.shape

(3, 3)

In [10]:
X.ndim

2

In [11]:
np.linalg.matrix_rank(X)

3

In [12]:
np.linalg.inv(X)

array([[ 0.04299495, -0.07659874, -0.00491918],
       [-0.08739539,  0.25228391,  0.00702741],
       [ 0.00773015, -0.0449754 ,  0.0154603 ]])

### Statistics

In [13]:
data = np.random.randint(10,100,20)

In [14]:
data

array([82, 35, 49, 61, 13, 24, 59, 71, 25, 28, 50, 26, 10, 86, 89, 18, 57,
       49, 52, 86])

In [15]:
np.mean(data)

48.5

In [16]:
np.median(data)

49.5

In [17]:
np.std(data)

24.868654969660103

In [18]:
np.var(data)

618.45

### Broadcasting

In [20]:
MData = np.array([[1,2],[5,2],[4,2]])
NData = np.array([[3,1],[4,1]])

In [28]:
OData = np.array([[2],[2],[2]])

In [21]:
MData.shape

(3, 2)

In [22]:
NData.shape

(2, 2)

In [29]:
OData.shape

(3, 1)

In [30]:
MData - OData

array([[-1,  0],
       [ 3,  0],
       [ 2,  0]])

In [31]:
MData - NData

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [32]:
MData.reshape(1,3,2)

array([[[1, 2],
        [5, 2],
        [4, 2]]])

In [33]:
NData.reshape(2,1,2)

array([[[3, 1]],

       [[4, 1]]])

In [35]:
res = MData.reshape(1,3,2) - NData.reshape(2,1,2)

In [36]:
res.shape

(2, 3, 2)

In [37]:
res

array([[[-2,  1],
        [ 2,  1],
        [ 1,  1]],

       [[-3,  1],
        [ 1,  1],
        [ 0,  1]]])

In [38]:
MData = np.array([[1,2,2],[5,2,1],[3,4,2]])
NData = np.array([[3,1,2],[1,4,1]])

In [39]:
MData.shape

(3, 3)

In [40]:
NData.shape

(2, 3)