In [1]:
import numpy as np

In [3]:
data = np.random.randint(1,100,(5,5))

In [4]:
data

array([[27, 26, 90, 90, 21],
       [21, 16, 20, 23, 14],
       [64, 27, 26, 31, 89],
       [48, 23, 97, 99, 80],
       [82, 66, 15,  2, 23]])

In [5]:
data.max()

99

In [7]:
data = np.random.randint(1,100,20)

In [8]:
max(data)

96

In [9]:
data

array([83,  8, 87, 47, 25, 81, 79, 91, 95, 25, 94, 22, 48, 22, 87, 96, 91,
       45, 22, 51])

In [10]:
data.max()

96

In [11]:
data = np.random.randint(1,100,(5,5))
data = data.reshape(25)

In [12]:
data

array([12, 98, 71, 36, 37, 87, 76,  3, 65, 28, 12, 14, 38, 57, 35, 65, 69,
       13, 21, 69, 55, 25, 86, 37, 23])

In [13]:
data = np.random.randint(1,100,(5,5))

In [14]:
data

array([[73, 21,  6, 55, 57],
       [63,  9, 41, 42, 87],
       [52, 39, 19,  7, 97],
       [59, 83, 40, 45,  2],
       [81, 82, 36,  6, 94]])

In [15]:
data.max(axis=0)

array([81, 83, 41, 55, 97])

In [16]:
data.max(axis=1)

array([73, 87, 97, 83, 94])

In [18]:
data.sum(axis=1)

array([212, 242, 214, 229, 299])

In [19]:
data = np.array([1,0,1])

In [20]:
data.any()

True

In [21]:
data.all()

False

In [23]:
data = np.array([0,0,0])

In [24]:
data.any()

False

In [25]:
data = np.array([10,10,10])

In [26]:
data.all()

True

In [28]:
np.choose([1,0,0,1,1,0], choices=['cat','rat'])

array(['rat', 'cat', 'cat', 'rat', 'rat', 'cat'], dtype='<U3')

In [30]:
data = np.random.randint(-10,10,20)

In [33]:
data

array([ -7,   1,   6,   8,  -9,   2,  -5,   4, -10,   8,   8,   0,   0,
         9,  -3,   0,   3,   3,   8,   9])

In [37]:
data[np.where(data > 0)]

array([1, 6, 8, 2, 4, 8, 8, 9, 3, 3, 8, 9])

In [36]:
data[[2,3,4]]

array([ 6,  8, -9])

In [38]:
data[data>0]

array([1, 6, 8, 2, 4, 8, 8, 9, 3, 3, 8, 9])

In [39]:
data = np.random.randint(1,10,(4,4))

In [44]:
np.where((data > 5) & (data <8))

(array([0, 1, 1, 2, 2]), array([3, 1, 2, 2, 3]))

In [41]:
data

array([[9, 1, 9, 6],
       [8, 6, 7, 4],
       [4, 1, 6, 6],
       [8, 1, 4, 9]])

In [45]:
data = np.random.randint(1,1000,100)

In [49]:
np.log2(data) * 10

array([56.72425342, 90.25139562, 90.02815016, 94.38791853, 96.14709844,
       76.58211483, 85.92457037, 94.03012024, 86.86500527, 98.13781191,
       94.99845887, 70.        , 96.51051691, 78.39203788, 88.20178962,
       94.63524373, 48.57980995, 68.57980995, 87.58223215, 98.15383296,
       72.2881869 , 37.00439718, 89.85841937, 77.61551232, 90.92757141,
       96.98704667, 88.29722735, 98.18582177, 93.66322214, 98.24958741,
       98.78050913, 62.2881869 , 97.7478706 , 60.        , 84.59431619,
       99.17372079, 95.83082768, 84.6760555 , 86.61778098, 94.00879436,
       70.        , 93.64134655, 85.31381461, 90.30667136, 38.07354922,
       74.26264755, 98.73444113, 97.3978061 , 97.1596199 , 82.99208018,
       74.51211112, 79.48367232, 99.48367232, 90.36173613, 85.0779464 ,
       98.16983623, 90.1402047 , 92.57387843, 65.39158811, 63.03780748,
       68.07354922, 81.13742166, 70.87462841, 91.16343961, 88.88743249,
       77.61551232, 91.21533517, 94.81799432, 96.65335917, 61.29

In [51]:
data[np.where(data > np.log2(data) * 10)]

array([521, 513, 694, 784, 202, 386, 677, 412, 900, 724, 128, 804, 229,
       452, 706, 116, 433, 901, 150, 507, 217, 546, 831, 455, 903, 660,
       907, 941,  75, 876,  64, 352, 967, 767, 354, 405, 676, 128, 659,
       370, 523, 172, 938, 855, 841, 315, 175, 247, 988, 525, 364, 902,
       517, 612,  93,  79, 112, 277, 136, 555, 474, 217, 557, 715, 812,
        70, 203, 179, 747, 580, 729, 205, 203, 544, 593, 385, 756, 371,
       430, 450, 572, 986, 552,  85, 546, 338, 907, 995, 468,  61, 528,
       624, 862, 448, 918])

In [53]:
a = np.array([12,22,25,6,2,2,2,11])

In [66]:
b = np.log2(a)

In [67]:
b = np.round(b,1)

In [58]:
a

array([12, 22, 25,  6,  2,  2,  2, 11])

In [70]:
b = b * 2 + 5

In [71]:
b

array([19.4, 23. , 23.4, 15.4,  9. ,  9. ,  9. , 19. ])

In [72]:
a < b

array([ True,  True, False,  True,  True,  True,  True,  True])

In [81]:
data = np.array([1177.698,2,7,2,2,2,62000])

In [78]:
data > 5

array([ True, False,  True, False, False, False,  True])

In [82]:
np.argmax(data)

6

In [83]:
data

array([1.177698e+03, 2.000000e+00, 7.000000e+00, 2.000000e+00,
       2.000000e+00, 2.000000e+00, 6.200000e+04])

In [84]:
np.argmin(data)

1