### Objectives
* Introduction & Concepts
* Properties of PCA
* Applications of PCA

<hr>

### Introduction
* Main idea is to reduce the dimensionality of the data
* Dimensions of data means columns in the data
* Feature selection means choosing important feature
* Dimensionality Reduction is about deriving new features (m) out of original features (n)
* m < n
* You don't want to compromise in accuracy.

* This is achieved by transforming variables(columns) to a new set of columns or variables which are known as principal component
* These principal components have a parameter telling how important they are in representing the data

In [1]:
from sklearn.decomposition import PCA

/home/awantik/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/awantik/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
breast_cancer_data = load_breast_cancer()

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
data = mm.fit_transform(breast_cancer_data.data)

In [9]:
data.shape

(569, 30)

In [10]:
pca = PCA(n_components=10)

In [12]:
res = pca.fit_transform(data)

In [13]:
res

array([[ 1.38702121,  0.42689533, -0.54170265, ..., -0.03945639,
         0.07759398,  0.1552841 ],
       [ 0.46230825, -0.55694674, -0.20517458, ...,  0.02064433,
        -0.07064091, -0.0852782 ],
       [ 0.95462147, -0.10970115, -0.1478484 , ...,  0.00736261,
        -0.05933649, -0.07368419],
       ...,
       [ 0.22631131, -0.28794577,  0.31522403, ...,  0.01570687,
        -0.10833543, -0.0769097 ],
       [ 1.67783369,  0.33594595,  0.296116  , ..., -0.09247415,
         0.08379483,  0.00543691],
       [-0.90506804, -0.10410875,  0.38285992, ...,  0.03943283,
        -0.01986498,  0.10546061]])

In [17]:
pca.explained_variance_

array([0.33133389, 0.10785038, 0.0443947 , 0.04000678, 0.02549742,
       0.01916637, 0.00986455, 0.00743488, 0.00616788, 0.00589966])

### Notes
* Scaling should be done before PCA
* Explained_variance tells how important those derived features are

In [19]:
pca.components_.shape

(10, 30)

In [21]:
import pandas as pd

In [23]:
df = pd.DataFrame({'A':[1,2,3,4,5],'B':[1,2,3,4,5]})

In [29]:
df

A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5

In [32]:
pca = PCA(n_components=1)

In [33]:
pca.fit_transform(df)

array([[ 2.82842712],
       [ 1.41421356],
       [-0.        ],
       [-1.41421356],
       [-2.82842712]])

In [27]:
pca.components_.shape

(1, 2)

In [28]:
df

A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5

In [34]:
df['C'] = 10

In [40]:
pca = PCA(n_components=1)

In [41]:
pca.fit_transform(df)

array([[ 2.82842712],
       [ 1.41421356],
       [-0.        ],
       [-1.41421356],
       [-2.82842712]])

In [38]:
pca.explained_variance_

array([5.00000000e+00, 4.29747739e-32, 0.00000000e+00])

In [39]:
df

A  B   C
0  1  1  10
1  2  2  10
2  3  3  10
3  4  4  10
4  5  5  10

In [43]:
from sklearn.preprocessing import StandardScaler

data = breast_cancer_data.data
target = breast_cancer_data.target

In [44]:
ss = StandardScaler()

In [47]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [46]:
from sklearn.pipeline import make_pipeline

In [78]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [68]:
pipeline = make_pipeline(StandardScaler(),PCA(n_components=10),DecisionTreeClassifier())

In [79]:
pipeline = make_pipeline(StandardScaler(),PCA(n_components=10),LogisticRegression())

In [80]:
pipeline

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('pca',
                 PCA(copy=True, iterated_power='auto', n_components=10,
                     random_state=None, svd_solver='auto', tol=0.0,
                     whiten=False)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [81]:
gs = GridSearchCV(pipeline, param_grid={'pca__n_components':[10,11,12,13,14]},cv=5)

In [82]:
trainX, testX, trainY, testY = train_test_split(data, target)

In [83]:
gs.fit(trainX,trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to '

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('pca',
                                        PCA(copy=True, iterated_power='auto',
                                            n_components=10, random_state=None,
                                            svd_solver='auto', tol=0.0,
                                            whiten=False)),
                                       ('logisticregression',
                                        LogisticRegression(C=1.0,
                                                           class_weight=None,
                                                           dual=...
                         

In [84]:
gs.best_params_

{'pca__n_components': 14}

In [85]:
gs.best_score_

0.9835680751173709

In [86]:
gs.score(testX,testY)

0.958041958041958

In [57]:
pipeline = make_pipeline(PCA(n_components=10),DecisionTreeClassifier())

In [64]:
pipeline = make_pipeline(DecisionTreeClassifier())

In [65]:
gs = GridSearchCV(pipeline,cv=5)

TypeError: __init__() missing 1 required positional argument: 'param_grid'

In [66]:
pipeline.fit(trainX,trainY)

Pipeline(memory=None,
         steps=[('decisiontreeclassifier',
                 DecisionTreeClassifier(class_weight=None, criterion='gini',
                                        max_depth=None, max_features=None,
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        presort=False, random_state=None,
                                        splitter='best'))],
         verbose=False)

In [61]:
gs.best_score_

0.9107981220657277

In [67]:
pipeline.score(testX,testY)

0.9440559440559441

In [63]:
data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [77]:
data.shape

(569, 30)

In [87]:
lr = LogisticRegression()

In [88]:
lr.fit(trainX,trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [89]:
lr.score(testX,testY)

0.916083916083916

### Advantages of using PCA
* Reduces dimension of the data thus improving training time
* Since the data is better represented, simple models(linear) might work better.