### Implement Nearest Neighbour without sklearn
* Recap of nearest Neighbour
* Implement Nearest Neighbour Classifier

### Algo:
1. During Training, data are stored in an optimized data structure suited for fast search.
2. During prediction, for each data we search for the nearest neighbours using euclidian/manhatten/humming distance vector calculation technique
3. Finally, decide based on majority

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
import pandas as pd

/home/awantik/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/awantik/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [9]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [10]:
df['type'] = iris.target

In [13]:
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
117                7.7               3.8                6.7               2.2   
139                6.9               3.1                5.4               2.1   
125                7.2               3.2                6.0               1.8   
76                 6.8               2.8                4.8               1.4   
78                 6.0               2.9                4.5               1.5   

     type  
117     2  
139     2  
125     2  
76      1  
78      1

In [14]:
def calculate_distance_between_vectors(v1,v2):
    pass

In [16]:
def store_training_data(train_data):
    pass

In [17]:
def find_k_neighbours(k,data):
    pass

In [18]:
def identify_class_from_neighbours(neighbours):
    pass

In [25]:
import numpy as np

In [129]:
class MyKNN:
    def __init__(self,k=5):
        self.k = k
        
    def my_fit(self, feature_data, target_data):
        self.feature_data = np.array(feature_data)
        self.target_data = np.array(target_data)
        
    def calculate_distance_vector_matrix(self, one_data):
        distances = np.sqrt(np.sum(np.square(self.feature_data - one_data),axis=1))
        return distances
    
    def find_k_neighbours(self,one_data_feature):
        res = self.calculate_distance_vector_matrix(one_data_feature)
        return res.argsort()[:self.k]
        
    def find_k_neighbours_class(self, one_data_feature):
        indexs_of_neighbours = self.find_k_neighbours(one_data_feature)
        return self.target_data[indexs_of_neighbours]
    
    def my_predict(self, one_data_feature):
        classes = self.find_k_neighbours_class(one_data_feature)
        return np.bincount(classes).argmax()

In [130]:
model = MyKNN(k=5)

In [131]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'type'],
      dtype='object')

In [101]:
feature_data = df.drop(columns=['type'],axis=1)
target_data = df.type

In [132]:
model.my_fit(feature_data, target_data)

* Can we calculate euclidian distance between one_data & comp_data in one shot
* Below is euclidian distance between one_data & all the comp_data

In [56]:
np.sqrt(np.sum(np.square(comp_data - one_data),axis=1))[:5]

array([6.00499792, 5.76281181, 5.69736781, 5.55517776, 5.96322061])

In [103]:
one_data

array([1, 2, 3, 4])

In [104]:
model.find_k_neighbours_class(one_data)

[2 1 1 1 1]


In [109]:
res = np.array([1,12,3,11,11])

In [110]:
res

array([ 1, 12,  3, 11, 11])

In [115]:
np.bincount(res).argmax()

11

In [137]:
model.my_predict([4,4,4,4])

2

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [139]:
help(KNeighborsClassifier)

Help on class KNeighborsClassifier in module sklearn.neighbors.classification:

class KNeighborsClassifier(sklearn.neighbors.base.NeighborsBase, sklearn.neighbors.base.KNeighborsMixin, sklearn.neighbors.base.SupervisedIntegerMixin, sklearn.base.ClassifierMixin)
 |  KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None, **kwargs)
 |  
 |  Classifier implementing the k-nearest neighbors vote.
 |  
 |  Read more in the :ref:`User Guide <classification>`.
 |  
 |  Parameters
 |  ----------
 |  n_neighbors : int, optional (default = 5)
 |      Number of neighbors to use by default for :meth:`kneighbors` queries.
 |  
 |  weights : str or callable, optional (default = 'uniform')
 |      weight function used in prediction.  Possible values:
 |  
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |        are weighted equally.
 |      - 'distance' : weight points by the inverse of th

### Assignment:
* Implement KNNRegressor