### Objectives
* Understanding Gradient Descent
* Calculating Graddient Descent
* Implement Gradient Descent

<hr>

* What is Gradient Descent?
* A. It's an algorithm to find out the (m,b) such that the cost is least.

<img src="https://github.com/edyoda/Data-Scientist-program/blob/master/Assignment/images/gd.png?raw=true">

* What is velocity?
- d(distance)/ dt

* What is acceleration?
- d(velocity)/ dt

* We have to find out how Loss changes with respect to weights(m & c)

### Now, we will find out how will Loss change w.r.t. m 

$d/dm (1/N /Sigma (y - (m*x + b)^2$

$d/dm (y - (m*x +b))^2$

$d/dm(y^2 -2*y*(m*x + b) + (m*x + b)^2)$
$d/dm(y^2 -2*y*m*x -2*y*b + m^2*x^2 + 2*m*x*b + b^2)$
$d/dm(-2*y*m*x + m^2*x^2 + 2*m*x*b)$
$-2*y*x + 2*m*x^2 + 2*x*b$
$-2*x(y -( m*x + b))$

* Identify the change in the weights such that the loss is reduced
* Using above methods, we calculate the new weights

In [1]:
from sklearn.datasets import make_regression

In [2]:
X,y = make_regression(n_features=1, n_samples=100, noise=3)

In [3]:
X

array([[ 1.27818437],
       [ 0.20275406],
       [-2.46742425],
       [-0.19525101],
       [-0.96435687],
       [-0.29773419],
       [ 1.90129057],
       [ 0.7493305 ],
       [ 1.93791531],
       [ 0.74147371],
       [-1.03049832],
       [-1.02893835],
       [-0.88334976],
       [-0.35886584],
       [ 0.85750504],
       [-0.66578017],
       [-0.67393301],
       [-0.30517878],
       [-0.91467954],
       [-0.85448383],
       [-1.46536985],
       [-0.8495231 ],
       [ 3.24164276],
       [ 0.95842703],
       [-1.31310558],
       [-0.76093838],
       [-0.04337911],
       [ 0.18417004],
       [-0.95630224],
       [-1.36457364],
       [ 1.2247135 ],
       [-0.93035763],
       [ 0.68402948],
       [ 0.77734812],
       [ 1.51320305],
       [-1.6782565 ],
       [-0.36293976],
       [-2.2145341 ],
       [ 1.1864367 ],
       [ 1.38395062],
       [ 0.98108679],
       [ 0.5872015 ],
       [ 0.29246631],
       [ 0.66916593],
       [-0.01879841],
       [-1

In [4]:
y

array([ 1.27601764e+02,  1.77557501e+01, -2.39475712e+02, -1.35555497e+01,
       -9.30029325e+01, -3.05095800e+01,  1.83236924e+02,  7.25090919e+01,
        1.84790648e+02,  7.42026257e+01, -9.58780598e+01, -1.02481119e+02,
       -8.88758242e+01, -3.36337387e+01,  8.30025888e+01, -6.59001704e+01,
       -6.73513415e+01, -2.64690084e+01, -9.17200829e+01, -8.39309868e+01,
       -1.45578301e+02, -8.53079357e+01,  3.14129476e+02,  9.54170317e+01,
       -1.29951646e+02, -7.37046417e+01, -2.62191298e+00,  1.39425161e+01,
       -9.34462748e+01, -1.26578580e+02,  1.16725132e+02, -9.02648430e+01,
        6.81224334e+01,  7.10031838e+01,  1.42778814e+02, -1.63104569e+02,
       -3.58987364e+01, -2.10275296e+02,  1.12195266e+02,  1.35254657e+02,
        9.65155297e+01,  6.04308185e+01,  2.39474258e+01,  7.12954635e+01,
        4.52121191e-01, -1.87852929e+02,  9.03991546e-01, -4.45408702e+01,
       -1.12916483e+02,  1.27065153e+02, -6.85971501e+01, -1.16824324e+02,
       -9.61923817e+01, -

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.scatter(X,y,s=10)
plt.xlabel('X')
plt.ylabel('y')

In [ ]:
X.shape

In [ ]:
import numpy as np

In [ ]:

def calc_grad_descent(m,b,X,y,learning_rate=0.01):
    N = len(X)
    y_pred = m*X+b
    SE = np.square(y.reshape(-1,1) - y_pred)
    SSE = np.sum(SE)
    MSE = 1/N*SSE
    print (MSE)
    
    delat_m = ??
    delta_b = ??
    
    new_m = m - delta_m
    new_b = b - delta_b
    
    m = new_m
    b = new_b
    
    y_pred = m*X+b
    SE = np.square(y.reshape(-1,1) - y_pred)
    SSE = np.sum(SE)
    MSE = 1/N*SSE
    print (MSE)
    
    
    

In [ ]:
calc_grad_descent(10,2,X,y)

<img src="<img src="https://github.com/edyoda/Data-Scientist-program/blob/master/Assignment/images/gd.png?raw=true">">

In [12]:
X = list(X[:,0])

In [13]:
y = list(y)

### Algorithm
* Initialize m,b with random values
* Learning rate is the jump size

In [14]:
def update_params(m,b,X,y,learning_rate=0.01):
    delta_m = 0
    delta_b = 0
    N = len(X)
    for i in range(N):
        delta_m += -2*X[i]*(y[i]- (m*X[i]+b))
        delta_b += -2*(y[i]- (m*X[i]+b))
        
    m -= (1/N)* learning_rate * (delta_m)
    b -= (1/N)* learning_rate * (delta_b)
    return (m,b)
    

In [15]:
update_params(10,5,X,y)

(12.135867787558139, 4.794815387427778)

In [7]:
update_params(10.45,4.92,X,y)

(array([12.57472343]), array([4.71697449]))

In [ ]:
X[:2]

In [16]:
import numpy as np
def calc_grad_desc(m,b,X,y):
    N = len(X)
    for i in range(20):
        SE = np.square(np.array(y) - (m*np.array(X) + b))
        SSE = np.sum(SE)
        MSE = (1/N)*SSE
        print (np.round(MSE,2),np.round(m,2),np.round(b,2))
        m,b = update_params(m,b,X,y)
        

In [17]:
calc_grad_desc(10,5,X,y)

9323.07 10 5
8868.36 12.14 4.79
8435.87 14.22 4.6
8024.51 16.25 4.4
7633.26 18.23 4.22
7261.11 20.17 4.04
6907.15 22.05 3.87
6570.49 23.89 3.7
6250.26 25.68 3.54
5945.69 27.43 3.38
5655.98 29.14 3.23
5380.43 30.8 3.08
5118.33 32.42 2.94
4869.04 34.01 2.81
4631.92 35.55 2.67
4406.37 37.06 2.55
4191.85 38.53 2.43
3987.79 39.96 2.31
3793.7 41.36 2.19
3609.08 42.72 2.08
