### Objectives
* Challenges with current code
* Understanding Pipeline
* Solving Problems using Pipeline
* Challenges with Pipeline
* Solving hetrogenous data problem with ColumnTransformer

<hr>

### Challenges with current code
* Dev have to do manually the preprocessing followed by putting the data in the estimators

In [1]:
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [4]:
digits.data.shape

(1797, 64)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
trainX, testX, trainY, testY = train_test_split(digits.data, digits.target)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
ss = StandardScaler()

In [10]:
trainX_tf = ss.fit_transform(trainX)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
rf = RandomForestClassifier()

In [14]:
rf.fit(trainX_tf, trainY)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [15]:
#This is incorrect, testX isn't tranformed
#rf.predict(testX)

In [16]:
testX_tf = ss.transform(testX)

In [17]:
rf.predict(testX_tf)

array([2, 1, 0, 2, 1, 8, 6, 9, 7, 4, 2, 0, 4, 8, 5, 8, 1, 0, 5, 9, 2, 5,
       2, 4, 1, 4, 5, 9, 1, 7, 4, 0, 1, 7, 3, 1, 8, 4, 0, 2, 6, 4, 5, 1,
       0, 4, 0, 8, 4, 3, 6, 4, 4, 4, 6, 4, 0, 5, 1, 3, 2, 3, 2, 0, 2, 2,
       1, 3, 3, 5, 5, 9, 9, 9, 4, 2, 5, 9, 4, 6, 8, 7, 5, 1, 3, 5, 6, 7,
       1, 9, 1, 6, 9, 4, 9, 6, 5, 1, 0, 6, 6, 3, 9, 9, 9, 5, 0, 8, 4, 7,
       3, 7, 3, 3, 6, 8, 9, 6, 1, 3, 4, 5, 1, 5, 2, 3, 7, 6, 1, 2, 3, 9,
       0, 2, 1, 3, 8, 1, 5, 5, 9, 6, 2, 1, 6, 7, 5, 0, 4, 2, 9, 9, 1, 9,
       8, 4, 4, 4, 2, 4, 0, 3, 7, 9, 2, 8, 0, 2, 7, 8, 6, 9, 7, 0, 7, 7,
       1, 5, 1, 2, 9, 4, 2, 4, 4, 3, 8, 2, 8, 9, 5, 5, 0, 7, 1, 9, 4, 0,
       9, 6, 2, 2, 3, 7, 2, 5, 6, 6, 8, 0, 3, 8, 9, 0, 8, 6, 7, 5, 8, 6,
       3, 8, 2, 2, 6, 4, 4, 0, 8, 0, 3, 1, 5, 8, 7, 8, 5, 6, 0, 3, 8, 1,
       4, 1, 1, 7, 3, 1, 8, 0, 8, 3, 3, 6, 4, 1, 9, 5, 4, 4, 2, 9, 1, 7,
       7, 2, 6, 6, 6, 7, 8, 7, 7, 7, 2, 7, 4, 4, 9, 4, 4, 0, 3, 5, 6, 9,
       3, 4, 0, 4, 0, 7, 0, 7, 5, 1, 6, 3, 9, 9, 1,

### Challenges
* Different features need differnt preprocessing
* It's very cumbersome to do things the current way
* We have to preserve manually all the preprocessors used

### Pipeline
* It connects preprocessor & estimators & thus removes the need to store them manually

In [18]:
from sklearn.pipeline import make_pipeline

In [19]:
digit_pipeline = make_pipeline(StandardScaler(), RandomForestClassifier())

In [21]:
digit_pipeline.fit(trainX, trainY)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [22]:
digit_pipeline.predict(testX)

array([2, 1, 0, 2, 1, 8, 6, 9, 7, 4, 2, 0, 4, 8, 5, 8, 1, 5, 5, 9, 2, 5,
       2, 7, 1, 4, 5, 9, 1, 7, 4, 0, 1, 7, 3, 1, 8, 9, 0, 2, 6, 4, 5, 1,
       0, 4, 0, 8, 4, 3, 6, 4, 4, 4, 6, 4, 0, 5, 1, 3, 2, 3, 2, 0, 2, 2,
       1, 3, 3, 5, 5, 8, 2, 9, 4, 2, 5, 9, 4, 6, 8, 7, 5, 1, 3, 5, 6, 4,
       1, 9, 1, 6, 9, 4, 9, 6, 5, 1, 0, 6, 6, 3, 3, 9, 9, 5, 6, 8, 4, 7,
       3, 7, 3, 3, 6, 8, 9, 6, 1, 3, 6, 5, 1, 5, 2, 9, 7, 6, 1, 2, 3, 9,
       0, 2, 1, 3, 8, 1, 5, 5, 7, 6, 2, 1, 6, 7, 5, 0, 5, 2, 9, 9, 1, 9,
       8, 4, 4, 4, 2, 4, 0, 3, 7, 9, 2, 8, 0, 2, 7, 8, 6, 9, 7, 0, 7, 7,
       1, 3, 1, 2, 9, 4, 2, 4, 4, 3, 8, 2, 8, 9, 9, 5, 0, 7, 1, 9, 4, 0,
       9, 6, 2, 2, 3, 7, 2, 5, 6, 6, 8, 0, 3, 8, 9, 0, 8, 6, 7, 5, 8, 6,
       8, 8, 3, 2, 6, 4, 4, 0, 8, 0, 3, 1, 5, 8, 7, 8, 5, 6, 0, 3, 8, 1,
       4, 1, 1, 7, 3, 1, 8, 0, 8, 3, 3, 6, 4, 1, 9, 5, 4, 4, 2, 9, 1, 7,
       7, 2, 6, 6, 6, 7, 8, 7, 7, 5, 2, 7, 4, 4, 9, 4, 4, 0, 3, 5, 6, 9,
       3, 4, 0, 4, 0, 7, 0, 7, 5, 1, 6, 3, 9, 7, 1,

In [27]:
digit_pipeline.steps[1][1].feature_importances_

array([0.        , 0.00122053, 0.01816807, 0.00857868, 0.0081789 ,
       0.01796291, 0.00409365, 0.00065628, 0.        , 0.00587447,
       0.0282883 , 0.00523326, 0.00950129, 0.03406862, 0.00783087,
       0.00072251, 0.        , 0.00481624, 0.01398047, 0.03426814,
       0.03692408, 0.04505838, 0.0101396 , 0.        , 0.        ,
       0.01494973, 0.04530306, 0.01642391, 0.03816368, 0.0218493 ,
       0.055166  , 0.        , 0.        , 0.0389982 , 0.02513865,
       0.01982917, 0.0324118 , 0.01760624, 0.01897851, 0.        ,
       0.00015879, 0.00665488, 0.0298063 , 0.04416555, 0.02701526,
       0.01689037, 0.02807224, 0.        , 0.        , 0.00447629,
       0.01159953, 0.02196495, 0.01660934, 0.03576797, 0.01421689,
       0.        , 0.        , 0.00487922, 0.01407126, 0.01246016,
       0.02156464, 0.02119958, 0.02395519, 0.0040881 ])

### Connecting Pipeline with Hyper-parameter Tuning
* We could determine the best combination of hyper-parameters for preprocessor & estimator

In [28]:
from sklearn.feature_selection import SelectKBest, f_classif

In [32]:
digit_pipeline = make_pipeline(StandardScaler(), SelectKBest(k=10, score_func=f_classif), RandomForestClassifier(n_estimators=100))

In [34]:
digit_pipeline

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('selectkbest',
                 SelectKBest(k=10,
                             score_func=<function f_classif at 0x7efd7e3d3f28>)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=None,
                                        oob_score=

In [33]:
from sklearn.model_selection import GridSearchCV

In [35]:
#params = {'selectkbest__k':[20,30,40], 'randomforestclassifier__n_estimators':[100,200]}

In [43]:
params = {'selectkbest__k':[50,55,60], 'randomforestclassifier__n_estimators':[200,250]}

In [44]:
gs = GridSearchCV(digit_pipeline, param_grid=params, cv=5, n_jobs=4)

In [45]:
gs.fit(trainX, trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [ 0 32 39] are constant.
  UserWarning)
/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('selectkbest',
                                        SelectKBest(k=10,
                                                    score_func=<function f_classif at 0x7efd7e3d3f28>)),
                                       ('randomforestclassifier',
                                        RandomForestClassifier(bootstrap=True,
                                                               class_weight=None,
                                                               criterion='gini',
                                                               max_dept...
                                   

In [46]:
gs.best_params_

{'randomforestclassifier__n_estimators': 200, 'selectkbest__k': 55}

In [47]:
gs.best_score_

0.9732739420935412

In [48]:
gs.predict(testX[:2])

array([2, 1])

In [49]:
gs.best_estimator_

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('selectkbest',
                 SelectKBest(k=55,
                             score_func=<function f_classif at 0x7efd7e3d3f28>)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=200, n_jobs=None,
                                        oob_score=

### Column Transformer for dealing with hetrogenous data
* Regular Pipeline intends to do same processing for all the columns
* This doesn't work for hetrogenous data

<img src="https://github.com/edyoda/Data-Scientist-program/blob/master/Assignment/images/ColumnTranformer.png?raw=true">

In [51]:
import pandas as pd

In [52]:
hr_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')

In [54]:
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [55]:
hr_data.sample(5)

satisfaction_level  last_evaluation  number_project  \
309                  0.10             0.94               6   
12579                0.39             0.55               2   
8683                 0.23             0.96               4   
12495                0.82             0.99               4   
4451                 0.87             0.68               5   

       average_montly_hours  time_spend_company  Work_accident  left  \
309                     285                   4              0     1   
12579                   159                   3              0     1   
8683                    213                   4              0     0   
12495                   263                   6              0     1   
4451                    187                   3              0     0   

       promotion_last_5years       dept  salary  
309                        0    support  medium  
12579                      0  technical    high  
8683                       0  technical  medium  
12495                      0  technical  medium  
4451                       0      sales     low

In [56]:
feature_data = hr_data.drop(columns=['left'])

In [57]:
target_data = hr_data.left

* Differnt columns needs differnt preprocessing

In [60]:
cat_data = feature_data.select_dtypes(include=['object'])

In [62]:
#satisfaction_level & last_evaluation don't need preprocessing
#number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years need MinMaxScaler
#dept & Salary need OrdinalEncoder
feature_data.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
promotion_last_5years      int64
dept                      object
salary                    object
dtype: object

In [63]:
float_data = feature_data.select_dtypes(include=['float'])

In [65]:
float_data[:4]

satisfaction_level  last_evaluation
0                0.38             0.53
1                0.80             0.86
2                0.11             0.88
3                0.72             0.87

In [66]:
int_data = feature_data.select_dtypes(include=['int'])

In [113]:
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer

In [69]:
#cat_pipeline = make_pipeline(SimpleImputer(),OrdinalEncoder())
#SimpleImpter is for handling missing data in pipeline

cat_pipeline = make_pipeline(OrdinalEncoder())

In [89]:
int_pipeline = make_pipeline(MinMaxScaler(), SelectKBest(k=3,score_func=f_classif))

In [90]:
from sklearn.compose import make_column_transformer

In [91]:
preprocessor = make_column_transformer(
              (cat_pipeline,cat_data.columns),
              (int_pipeline,int_data.columns),
              remainder='passthrough'
)

In [92]:
pipeline = make_pipeline(preprocessor, RandomForestClassifier())

In [93]:
trainX,testX, trainY, testY = train_test_split(feature_data, target_data)

In [94]:
trainX[:2]

satisfaction_level  last_evaluation  number_project  \
14443                0.11             0.83               6   
12791                0.82             0.49               4   

       average_montly_hours  time_spend_company  Work_accident  \
14443                   244                   4              0   
12791                   276                   4              0   

       promotion_last_5years        dept salary  
14443                      0  accounting    low  
12791                      0     support    low

In [95]:
pipeline.fit(trainX, trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('pipeline-1',
                                                  Pipeline(memory=None,
                                                           steps=[('ordinalencoder',
                                                                   OrdinalEncoder(categories='auto',
                                                                                  dtype=<class 'numpy.float64'>))],
                                                           verbose=False),
                                                  Index(['dept', 'salary'], dtype='object')),
                                                 ('pipe...
                 RandomForestClassifier(bootstrap=True, class_weight=None,
        

In [96]:
pipeline.predict(testX[:2])

array([0, 0])

In [97]:
pipeline.score(testX,testY)

0.9866666666666667

In [100]:
pipeline.steps[0][1].transformers

[('pipeline-1', Pipeline(memory=None,
           steps=[('ordinalencoder',
                   OrdinalEncoder(categories='auto',
                                  dtype=<class 'numpy.float64'>))],
           verbose=False), Index(['dept', 'salary'], dtype='object')),
 ('pipeline-2', Pipeline(memory=None,
           steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                  ('selectkbest',
                   SelectKBest(k=3,
                               score_func=<function f_classif at 0x7efd7e3d3f28>))],
           verbose=False), Index(['number_project', 'average_montly_hours', 'time_spend_company',
         'Work_accident', 'promotion_last_5years'],
        dtype='object'))]

In [101]:
params = {'columntransformer__pipeline-2__selectkbest__k':[2,3]}

In [102]:
gs = GridSearchCV(pipeline, param_grid=params, n_jobs=4, cv=5)

In [103]:
gs.fit(trainX,trainY)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('columntransformer',
                                        ColumnTransformer(n_jobs=None,
                                                          remainder='passthrough',
                                                          sparse_threshold=0.3,
                                                          transformer_weights=None,
                                                          transformers=[('pipeline-1',
                                                                         Pipeline(memory=None,
                                                                                  steps=[('ordinalencoder',
                                                                                          OrdinalEncoder(categories='auto',
                                                                                                         dtype

In [104]:
gs.best_params_

{'columntransformer__pipeline-2__selectkbest__k': 3}

In [105]:
gs.best_score_

0.9847986487687794

### Disadvantages of Pipeline
* Doesn't support Online Learning
* Online Learning will be discussed later

### Dealing with imbalanced data in pipeline
* Use imblearn make_pipeline rather than scikit make_pipeline as RandomOverSampler is not supported in scikit

In [106]:
target_data.value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [109]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.pipeline import make_pipeline

In [110]:
#This make_pipeline is not scikit pipeline but imblearn pipeline which support Oversampler as part of pipeline
pipeline = make_pipeline(preprocessor, RandomOverSampler(), RandomForestClassifier())

In [111]:
pipeline.fit(trainX, trainY)

/home/awantik/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('pipeline-1',
                                                  Pipeline(memory=None,
                                                           steps=[('ordinalencoder',
                                                                   OrdinalEncoder(categories='auto',
                                                                                  dtype=<class 'numpy.float64'>))],
                                                           verbose=False),
                                                  Index(['dept', 'salary'], dtype='object')),
                                                 ('pipe...
                 RandomForestClassifier(bootstrap=True, class_weight=None,
        

In [112]:
pipeline.score(testX,testY)

0.9864