In [1]:
import numpy as np

### Creation of NumPy

In [6]:
a = np.zeros(4)

In [7]:
b = np.zeros((4,4))

In [8]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
c = np.zeros((3,3,3))

In [13]:
c.shape

(3, 3, 3)

In [14]:
np.ones(2)

array([1., 1.])

In [18]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
np.full((4,4),"Hello")

array([['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello']], dtype='<U5')

In [20]:
np.random.randint(1,10,(3,3))

array([[7, 2, 4],
       [7, 5, 2],
       [3, 5, 5]])

In [21]:
np.random.randint(1,10,(3,3))

array([[4, 6, 2],
       [1, 9, 8],
       [3, 1, 9]])

In [23]:
np.random.rand()

0.2135114114439025

In [25]:
z = np.array([12,33,55])

In [26]:
z.shape

(3,)

In [28]:
z.ndim

1

In [30]:
z.size

3

In [31]:
#Create an random number array of 3D of size (5,4,3). Data range (100,200)

In [33]:
data = np.random.randint(100,200,(5,4,3))

In [35]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [36]:
np.random.rand(3,3)

array([[0.56771097, 0.61682269, 0.32003874],
       [0.27982255, 0.92123116, 0.5833636 ],
       [0.70056846, 0.21090475, 0.43787477]])

In [37]:
data.shape

(5, 4, 3)

In [38]:
data.ndim

3

In [39]:
data.size

60

In [40]:
data

array([[[113, 149, 140],
        [123, 179, 156],
        [195, 197, 131],
        [159, 129, 164]],

       [[146, 153, 185],
        [196, 135, 129],
        [147, 157, 177],
        [170, 137, 150]],

       [[138, 110, 119],
        [135, 169, 151],
        [191, 147, 175],
        [115, 147, 113]],

       [[186, 171, 138],
        [178, 102, 153],
        [175, 121, 131],
        [109, 100, 184]],

       [[112, 116, 135],
        [120, 106, 149],
        [198, 141, 102],
        [108, 117, 138]]])

### Access NumPy

In [41]:
data = np.random.randint(10,100,(5,4))

In [44]:
data

array([[72, 99, 62, 71],
       [74, 87, 91, 29],
       [82, 51, 42, 68],
       [99, 94, 45, 83],
       [67, 85, 78, 11]])

In [46]:
data[2:4]

array([[82, 51, 42, 68],
       [99, 94, 45, 83]])

In [50]:
data[1:3,2:4]

array([[91, 29],
       [42, 68]])

In [52]:
data[:2,:2]

array([[72, 99],
       [74, 87]])

In [60]:
#an assignment on this topic
data[[1,4],2:4]

array([[91, 29],
       [78, 11]])

### ReShaping

In [61]:
data = np.arange(10)

In [62]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
new_data = data.reshape(2,5)

In [65]:
new_data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
new_data.shape

(2, 5)

In [68]:
#Assignment
new_data.reshape(-1,2).shape

(5, 2)

In [69]:
new_data.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
new_data.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Splitting & Stacking

In [79]:
data = np.random.randint(10,100,(4,6))

In [88]:
a,b = np.hsplit(data,[2])

In [89]:
a

array([[80, 85],
       [95, 17],
       [87, 67],
       [63, 40]])

In [90]:
b

array([[85, 63, 25, 51],
       [97, 26, 79, 72],
       [38, 28, 71, 91],
       [72, 97, 98, 40]])

In [84]:
a,b,c = np.vsplit(data,[2,3])

In [85]:
a

array([[80, 85, 85, 63, 25, 51],
       [95, 17, 97, 26, 79, 72]])

In [86]:
b

array([[87, 67, 38, 28, 71, 91]])

In [87]:
c

array([[63, 40, 72, 97, 98, 40]])

In [91]:
a

array([[80, 85],
       [95, 17],
       [87, 67],
       [63, 40]])

In [92]:
b

array([[85, 63, 25, 51],
       [97, 26, 79, 72],
       [38, 28, 71, 91],
       [72, 97, 98, 40]])

In [94]:
np.hstack([a,b])

array([[80, 85, 85, 63, 25, 51],
       [95, 17, 97, 26, 79, 72],
       [87, 67, 38, 28, 71, 91],
       [63, 40, 72, 97, 98, 40]])