### Calculating Vector Distances
* Understanding vectors
* Euclidian Distance
* Manhatten Distance
* Minkowiski Distance
* Cosine Distance

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [5]:
import pandas as pd

In [7]:
house_price = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt', index_col='Unnamed: 0')

In [9]:
house_price[['Sqft','Bedroom','Price']]

Sqft  Bedroom  Price
1    1177.698        2  62000
2    2134.800        4  78000
3    1138.560        2  58000
4    1458.780        3  45000
5     967.776        3  45000
..        ...      ...    ...
644  1359.156        3  45000
645   377.148        1  24800
646   740.064        1  45000
647  1707.840        3  65000
648  1376.946        3  36000

[645 rows x 3 columns]

In [ ]:
X = [11,22,33]
Y = [24,21,4]

Sqrt((11-24)^2 + (22-21)^2 + (33-4)^2)

In [10]:
from sklearn.metrics.pairwise import euclidean_distances,cosine_distances,manhattan_distances

In [12]:
euclidean_distances([[1,3]],[[2,2]])

array([[1.41421356]])

In [13]:
np.sqrt(2)

1.4142135623730951

In [14]:
house_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt', index_col='Unnamed: 0')

In [16]:
house_data = house_data[['Sqft','Bedroom','Price']]

In [18]:
np.round(euclidean_distances(house_data[:5]),2)

array([[    0.  , 16028.6 ,  4000.19, 17002.32, 17001.3 ],
       [16028.6 ,     0.  , 20024.8 , 33006.92, 33020.63],
       [ 4000.19, 20024.8 ,     0.  , 13003.94, 13001.12],
       [17002.32, 33006.92, 13003.94,     0.  ,   491.  ],
       [17001.3 , 33020.63, 13001.12,   491.  ,     0.  ]])

In [19]:
house_data[:5]

Sqft  Bedroom  Price
1  1177.698        2  62000
2  2134.800        4  78000
3  1138.560        2  58000
4  1458.780        3  45000
5   967.776        3  45000

In [20]:
np.round(manhattan_distances(house_data[:5]),2)

array([[    0.  , 16959.1 ,  4039.14, 17282.08, 17210.92],
       [16959.1 ,     0.  , 20998.24, 33677.02, 34168.02],
       [ 4039.14, 20998.24,     0.  , 13321.22, 13171.78],
       [17282.08, 33677.02, 13321.22,     0.  ,   491.  ],
       [17210.92, 34168.02, 13171.78,   491.  ,     0.  ]])

In [22]:
euclidean_distances(house_data).shape

(645, 645)

In [39]:
dist = euclidean_distances(house_data, house_data[:1])

In [41]:
res = dist.reshape(645)

In [49]:
dist_ser = pd.Series(res)

In [56]:
dist_ser.sort_values(ascending=True)[:5]

0         0.000000
354    1010.584678
319    1359.854329
379    1419.111272
269    2006.398817
dtype: float64

In [55]:
house_data.loc[[0, 354, 319, 379, 269]]

/home/awantik/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Sqft  Bedroom    Price
0         NaN      NaN      NaN
354  1384.062      3.0  49800.0
319  1700.724      2.0  55000.0
379  1167.024      3.0  38000.0
269   665.346      1.0  25000.0

In [57]:
np.cos(0)

1.0

In [58]:
a = np.array([1,2,3])

In [59]:
np.dot(a,a)

14

In [76]:
X = [[2, 2]]
Y = [[200,200]]

In [77]:
np.round(cosine_distances(X,Y),2)

array([[0.]])

* Cosine similarity is useful for text data analysis

In [78]:
np.round(cosine_distances(X,Y),2)

array([[0.]])

In [79]:
euclidean_distances(X,Y)

array([[280.01428535]])