# NumPy: Practice Problem 3: Solution
Easy Questions :

Moderate Questions :

Hard Questions :
<hr>

In [3]:
import numpy as np

### 1. Find dot product of two arrays.

a = [2j, 3j],

b = [2j, 3j]

Level: Easy

In [4]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

### 2. Create two arrays of 2-D and find dot product of it.

Level: Easy

In [7]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

### 3. Find vector product of given array.

a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

Level: Easy

In [9]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a,b)

(70-8j)

### 4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.

a = [[ 0  1  2  3]
     [ 4  5  6  7]
     [ 8  9 10 11]]

b = [[12 13 14 15]
     [16 17 18 19]
     [20 21 22 23]]

Level: Easy

In [13]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
np.inner(a, b)


array([[ 14,  38,  62],
       [ 86, 110, 134]])

### 5. Using given two array try to print out 3rd given array.

a = np.array(['a', 'b', 'c'], dtype=object)
b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']]
       
Level: Medium

In [16]:
a = np.array(['a', 'b', 'c'], dtype=object)
b = np.array([1,2,3])
np.outer(a,b)

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

### 6. Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8

Level: Medium

In [17]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

### 7. Check the following solution is right or wrong uisng numpy utilities.

2x+3y=8
3x+y=5

solution: x=1 , y=2

Level : Medium

In [24]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
x = np.array([1,2])
np.allclose(np.dot(a, x), b)

True

### 9. Write a program to add two arrays of different shape.
Hint: Broadcasting 

Level: Medium 

sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

In [26]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

### 10. Create a 3 * 3 array find it's diagonal using numpy utilities.

Level: Hard

In [63]:
a =np.arange(9).reshape(3,3)
print("diagonal:\n",a.diagonal())
print("matrix:\n",a)

diagonal:
 [0 4 8]
matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### 11. Now find anti - diagonal in previous question using horizontal and vector flip.

Level: Hard

In [72]:
a =np.arange(9).reshape(3,3)
print("using horizontal flip:\n",np.fliplr(a).diagonal())
print("using vertical flip:\n",np.flipud(a).diagonal())
print("matrix:\n",a)


using horizontal flip:
 [2 4 6]
using vertical flip:
 [6 4 2]
matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### 12. Create given array without using indexing.

a =   [[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]]

Level : Hard

In [74]:
a = np.zeros((7, 3), int)
np.fill_diagonal(a, 4, wrap=True)
a

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])