# NumPy: Practice Problem 3: Solution
Easy Questions :

Moderate Questions :

Hard Questions :
<hr>

### 1. Find dot product of two arrays.

a = [2j, 3j],

b = [2j, 3j]

Level: Easy

### 2. Create two arrays of 2-D and find dot product of it.

Level: Easy

### 3. Find vector product of given array.

a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

Level: Easy

### 4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.

a = [[ 0  1  2  3]
     [ 4  5  6  7]
     [ 8  9 10 11]]

b = [[12 13 14 15]
     [16 17 18 19]
     [20 21 22 23]]

Level: Easy

### 5. Using given two array try to print out 3rd given array.

a = np.array(['a', 'b', 'c'], dtype=object)
b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']]
       
Level: Medium

### 6. Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8

Level: Medium

### 7. Check the following solution is right or wrong uisng numpy utilities.

2x+3y=8
3x+y=5

solution: x=1 , y=2

Level : Medium

### 9. Write a program to add two arrays of different shape.
Hint: Broadcasting 

Level: Medium 

sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

### 10. Create a 3 * 3 array find it's diagonal using numpy utilities.

Level: Hard

### 11. Now find anti - diagonal in previous question using horizontal and vector flip.

Level: Hard

### 12. Create given array without using indexing.

a =   [[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]]

Level : Hard