## NumPy : Practice Problems 1: Solutions
Easy Questions :
Moderate Questions :
Hard Questions :
<hr>


### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy

In [2]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\CodeLover\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy

In [2]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  Create a vector with values ranging from 10 to 49.

Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically

Level: Easy

In [21]:
a=np.array([1,5,6,8,9],[1,2,5,4])
b=np.array([5,6])
np.vstack([a,b])

TypeError: data type not understood

### 4. Reverse a vector (first element becomes last).

Level: Easy

In [23]:
np.flip(a,0)

array([5, 1])

### 5. Create a 3x3 matrix with values ranging from 0 to 8 

Level: Easy

In [25]:
np.random.randint(0,8,(3,3))

array([[7, 5, 2],
       [4, 7, 5],
       [4, 3, 4]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy

In [27]:
a = np.array([1,2,0,0,4,0])
ind = []
for i,v in enumerate(a):
    if v!=0:
        ind.append(i)
ind

[0, 1, 4]

### 7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy

In [38]:
a = np.random.randint(0,100,(10,10))
a
a.max()
a.min()

1

### 8. Create a random vector of size 30 and find the mean value.

Level: Medium

In [40]:
a = np.random.randint(0,100,(30))
a
a.mean()

53.63333333333333

### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [42]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array

Level: Medium

In [43]:
np.pad(oneborder, (1,1), mode = 'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:
    
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
 
 Level: Medium

In [49]:
a=np.zeros((5,5))
a
a[1,0]=1
a[2,1]=2
a[3,2]=3
a[4,3]=4
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [51]:
a = np.random.random((5,5))
# normalization
b= (a - a.min())/(a.max()-a.min())
b


array([[0.53088363, 0.39689752, 0.55285447, 0.35206264, 0.58808469],
       [0.50701933, 0.21810595, 0.22481709, 0.46556647, 0.95140884],
       [0.66084707, 0.49560803, 0.95722694, 0.30885374, 0.76532993],
       [0.        , 0.710104  , 0.35589934, 0.88850812, 0.43920146],
       [0.6965616 , 0.14573397, 1.        , 0.56884303, 0.94326254]])

### 13. How to find common values between two arrays
Level: Medium

In [52]:
a1 = np.arange(25)
a2 = np.arange(10,51)
a3 = np.intersect1d(a1,a2)
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

In [56]:
def generator():
    global a
    a = np.array(np.arange(10))
generator()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 15. Subtract the mean of each row of a matrix
Level: Hard

In [57]:
arr = np.random.random((10,5))
means = np.mean(arr, axis = 1)
subs = arr.copy()
for i in range(arr.shape[0]):
    subs[i] = subs[i] - means[i]
print(subs)

[[-0.30351798  0.09446584 -0.2361642   0.56195963 -0.11674329]
 [ 0.3834771   0.48910973 -0.42901198 -0.26129163 -0.18228323]
 [-0.28196379 -0.19364019  0.08914285 -0.20833586  0.59479699]
 [-0.09819244  0.23106214  0.34494485 -0.14669631 -0.33111824]
 [ 0.21304116  0.12387445 -0.42097365 -0.02201374  0.10607177]
 [ 0.2437462   0.08353877  0.12343311  0.11482338 -0.56554145]
 [ 0.04891245  0.17970536  0.30257937 -0.14667102 -0.38452616]
 [ 0.24223282 -0.27676651  0.23874331  0.10181656 -0.30602618]
 [ 0.01599128 -0.23164976 -0.01406749 -0.17430177  0.40402775]
 [-0.08132798 -0.25650563 -0.001914    0.24873434  0.09101327]]


### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
Level: Hard

In [59]:
a =np.random.randint(0,10,(1,3))
b=np.random.randint(0,10,(3,1))
sums = []
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(np.array(sums).reshape(3,3))

[[12  9 10]
 [13 10 11]
 [13 10 11]]


### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard

In [61]:
v = np.linspace(5, 50, 10)
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])