## NumPy : Practice Problems 1
Easy Questions : 7
Moderate Questions : 7
Hard Questions : 3
<hr>


### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy

In [1]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\CodeLover\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy

In [2]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  Create a vector with values ranging from 10 to 49.

Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically

Level: Easy

### 4. Reverse a vector (first element becomes last).

Level: Easy

### 5. Create a 3x3 matrix with values ranging from 0 to 8 

Level: Easy

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy

### 7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy

### 8. Create a random vector of size 30 and find the mean value.

Level: Medium

### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [3]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array

Level: Medium

### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:
    
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
 
 Level: Medium

### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

### 13. How to find common values between two arrays
Level: Medium

### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

### 15. Subtract the mean of each row of a matrix
Level: Hard

### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
Level: Hard

### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard